var a=Math.sqrt(25);
document.write(a+"<br>");
document.write(Math.abs(-5)+"<br>");
document.write(Math.sin(30)+"<br>");
document.write(Math.pow(4,2)+"<br>");
document.write(Math.floor(6.33)+"<br>");
document.write(Math.ceil(6.33)+"<br>");
document.write(Math.round(4.2)+"<br>");
document.write(Math.max(4,2,10,9,5)+"<br>");
document.write(Math.min(4,2,10,9,5)+"<br>");
document.write(Math.random()+"<br>");
document.write(Math.random()*6+"<br>");
document.write(Math.floor(Math.random()*6)+"<br");
document.write(Math.floor(Math.random()*4)+1+"<br");